[package]
name = "apocalypse"
version = "0.1.0"
license = "MIT"
description = "Simple actor framework for Rust"
repository = "https://github.com/Malanche/apocalypse.git"
authors = ["Carlos Malanche <carlos.malanche.f@gmail.com>"]
edition = "2018"
keywords = ["actor"]

[features]
debug = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
async-trait = "0.1.51"
tokio = {version = "1.11.0", features = ["full"]}
futures = "0.3.17"
serde = {version = "1.0.130", features = ["derive"]}
bincode = "1.3.3"

[dev-dependencies]
criterion = {version = "0.3.5", features = ["async_futures"]}

[[bench]]
name = "per_second"
harness = false