[package]
name = "apocalypse"
version = "0.4.4"
license = "MIT"
description = "Simple actor framework for Rust"
repository = "https://github.com/Malanche/apocalypse.git"
authors = ["Carlos Malanche <carlos.malanche.f@gmail.com>"]
edition = "2018"
keywords = ["actor"]

[features]
full_log = []
ws = ["cataclysm", "bytes"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {version = "0.4.14", features = ["std"]}
async-trait = "0.1.51"
tokio = {version = "1.11.0", features = ["full"]}
futures = "0.3.17"
serde = {version = "1.0.130", features = ["derive"]}
bincode = "1.3.3"
bytes = {version = "1.1.0", optional = true}
cataclysm = {path = "../cataclysm/cataclysm", version = "0.2.0-beta.11", features=["stream", "ws"], optional = true}

[dev-dependencies]
criterion = {version = "0.3.5", features = ["async_tokio"]}
colored = "2.0.0"
winapi = "0.3.9"
chrono = "0.4.19"

[[bench]]
name = "per_second"
harness = false